apiVersion: v1
kind: PersistentVolume

metadata:
  name: k8s-mysql-pv

spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kisara71/mysql