apiVersion: v1
kind: Service

metadata:
  name: k8s-mysql-service
spec:
  selector:
    app: k8s-mysql
  ports:
    - port: 13306
      protocol: TCP
      targetPort: 3306
      nodePort: 30006
  type: NodePort