apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-mysql-dpm
  labels:
    app: k8s-mysql-dpm

spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mysql
  template:
    metadata:
      labels:
        app: k8s-mysql
    spec:
      containers:
        - name: k8s-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: k8s-mysql-storage
      volumes:
        - name: k8s-mysql-storage
          persistentVolumeClaim:
            claimName: webook-mysql-claim
      restartPolicy: Always
